spring:
  application:
    name: users-dev
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: pass1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create